name: Maven Develop CI Workflow

on:
  push:
    branches:
      - 'develop'

jobs:
  build-develop:
    runs-on: ubuntu-latest
    name: Develop CI Workflow
    permissions:
      checks: write
      actions: write
      contents: write
    concurrency:
      # The commit SHA or the branch name of the pull request. See: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
      group: ${{ github.event_name == 'pull_request' && github.head_ref || github.sha}}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: ./.github/workflows/template/java-setup.yml
        with:
          java-version: '21'
      - name: Build with Maven
        uses: ./.github/workflows/template/build-project.yml
        with:
          maven-goal: 'clean install'
          build-docker: true
