name: Maven Feature CI Workflow

on:
  pull_request:
    branches:
      - 'develop'
      - 'feature/**'

jobs:
  build-feature:
    runs-on: ubuntu-latest
    name: Feature CI Workflow
    env:
      CODEARTIFACT_AUTH_LOGIN: aws
    permissions:
      checks: write
      actions: write
      contents: write
    concurrency:
      # The commit SHA or the branch name of the pull request. See: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
      group: ${{ github.event_name == 'pull_request' && github.head_ref || github.sha}}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get branch names
        uses: tj-actions/branch-names@v8
        id: branch-names
      - name: Change Project Version
        run: |
          export BRANCH_NAME=${{steps.branch-names.outputs.current_branch}}
          ./mvnw versions:set -DnewVersion=${BRANCH_NAME##*/}-SNAPSHOT versions:commit
      - name: Set up JDK
        uses: ./.github/workflows/template/java-setup.yml
        with:
          java-version: '21'
      - name: Build with Maven
        uses: ./.github/workflows/template/build-project.yml
        with:
          maven-goal: 'clean install'
          build-docker: true

