name: Maven Master Release CI Workflow

on:
  push:
    branches: [ main ]

jobs:
  build-master:
    permissions:
      checks: write
      actions: write
      contents: write
    runs-on: ubuntu-latest
    name: Master CI Workflow
    env:
      CODEARTIFACT_AUTH_LOGIN: aws
    concurrency:
      # The commit SHA or the branch name of the pull request. See: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
      group: ${{ github.event_name == 'pull_request' && github.head_ref || github.sha}}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: maven
      - name: Build with Maven
        if: success()
        run: ./mvnw install --no-snapshot-updates --batch-mode --no-transfer-progress
      - name: Publish Surefire Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1

