name: Maven Master Release CI Workflow

on:
  push:
    branches: [ main ]

jobs:
  build-master:
    permissions:
      checks: write
      actions: write
      contents: write
    runs-on: ubuntu-latest
    name: Master CI Workflow
    env:
      CODEARTIFACT_AUTH_LOGIN: aws
    concurrency:
      # The commit SHA or the branch name of the pull request. See: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
      group: ${{ github.event_name == 'pull_request' && github.head_ref || github.sha}}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: ./.github/actions/java-setup
        with:
          java-version: '21'
      - name: Build with Maven
        uses: ./.github/actions/build-project
        with:
          maven-goal: 'clean install'
          build-docker: true

