name: Maven Prepare Master Release CI Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to be released"
        required: true
        type: string

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    name: Prepare Release CI Workflow
    permissions:
      checks: write
      actions: write
      contents: write
    concurrency:
      # The commit SHA or the branch name of the pull request. See: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
      group: ${{ github.event_name == 'pull_request' && github.head_ref || github.sha}}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Setup Git User
        uses: fregante/setup-git-user@v2
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: maven
      - name: Start Release Version
        run: ./mvnw -X com.amashchenko.maven.plugin:gitflow-maven-plugin:1.21.0:release-start -DreleaseRebase=true -DskipTestProject=true -B -DreleaseVersion=${{github.event.inputs.version}} -DgitFlowConfig.productionBranch=main

      - name: Generate Changelog
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Finish Release Version
        run: ./mvnw -X com.amashchenko.maven.plugin:gitflow-maven-plugin:1.21.0:release-finish -DreleaseRebase=true -DskipTestProject=true -B -DreleaseVersion=${{github.event.inputs.version}} -DgitFlowConfig.productionBranch=main