name: Maven Prepare Release CI Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to be released"
        required: true
        type: string

jobs:
  build-jdk21:
    runs-on: [ self-hosted, linux, x64 ]
    name: Build project
    permissions:
      pages: write
      checks: write
      actions: write
      contents: write
      pull-requests: write
    concurrency:
      # The commit SHA or the branch name of the pull request. See: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
      group: ${{ github.event_name == 'pull_request' && github.head_ref || github.sha}}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Git User
        uses: fregante/setup-git-user@v2
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: maven
      - name: Release Version
        run: ./mvnw com.amashchenko.maven.plugin:gitflow-maven-plugin:1.21.0:release-start com.amashchenko.maven.plugin:gitflow-maven-plugin:1.21.0:release-finish -DreleaseRebase=true -DskipTestProject=true -B -DreleaseVersion=${{github.event.inputs.version}} -DgitFlowConfig.productionBranch=main
