name: Generate release changelog and create release CI Workflow

on:
  push:
    tags:
      - '*'

jobs:
  build-master:
    permissions:
      actions: write
      contents: write
    runs-on: ubuntu-latest
    name: Generate release changelog and create release CI Workflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          draft: false
          prerelease: false

