name: Maven Prepare Master Release CI Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to be released"
        required: true
        type: string

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    name: Prepare Release CI Workflow
    permissions:
      checks: write
      actions: write
      contents: write
    concurrency:
      # The commit SHA or the branch name of the pull request. See: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
      group: ${{ github.event_name == 'pull_request' && github.head_ref || github.sha}}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Setup Git User
        uses: fregante/setup-git-user@v2
      - name: Release Version
        run: ./mvnw com.amashchenko.maven.plugin:gitflow-maven-plugin:1.21.0:release-start com.amashchenko.maven.plugin:gitflow-maven-plugin:1.21.0:release-finish -DreleaseRebase=true -DskipTestProject=true -B -DreleaseVersion=${{github.event.inputs.version}} -DgitFlowConfig.productionBranch=main